import os
import json
from pathlib import Path
from typing import Optional, Union

# PlatformIO provides `env` and `projenv` via SCons
try:
    Import("env", "projenv")  # type: ignore # noqa: F821
except Exception:
    # Fallback for static analysis
    env = None
    projenv = None


def parse_dotenv(dotenv_path: Path) -> dict:
    data: dict[str, str] = {}
    if not dotenv_path.exists():
        return data
    for line in dotenv_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" not in line:
            continue
        k, v = line.split("=", 1)
        k = k.strip()
        v = v.strip()
        # strip quotes if present
        if (v.startswith('"') and v.endswith('"')) or (v.startswith("'") and v.endswith("'")):
            v = v[1:-1]
        data[k] = v
    return data


def quote_define(value: str) -> str:
    # Use JSON to safely quote/escape for C/C++ defines
    return json.dumps(value)


def main() -> None:
    # Robustly resolve the PlatformIO project directory without relying on __file__
    if 'env' in globals() and env is not None:
        project_dir = Path(env.subst("$PROJECT_DIR"))
    elif '__file__' in globals():
        project_dir = Path(__file__).resolve().parent
    else:
        project_dir = Path(os.getcwd())
    repo_root = project_dir.parent
    dotenv = parse_dotenv(repo_root / ".env")

    def read_env(key: str) -> Optional[str]:
        return os.environ.get(key) or dotenv.get(key)

    ssid = read_env("ESP32_WIFI_SSID")
    pwd = read_env("ESP32_WIFI_PASSWORD")

    # Server URL priority: explicit ESP32_DEFAULT_SERVER_URL, then APP_URL, then default
    server_url = (
        read_env("ESP32_DEFAULT_SERVER_URL")
        or read_env("APP_URL")
        or "https://proyecto.bisonbyte.io"
    )

    device_id_raw = read_env("ESP32_DEVICE_ID")
    activation_key = read_env("ESP32_ACTIVATION_KEY")
    http_activation = read_env("ESP32_HTTP_ENDPOINT")
    http_state = read_env("ESP32_HTTP_STATE_ENDPOINT")
    http_set = read_env("ESP32_HTTP_SET_ENDPOINT")
    http_telemetry = read_env("ESP32_HTTP_TELEMETRY_ENDPOINT")
    poll_seconds_raw = read_env("ESP32_HTTP_POLL_SECONDS")

    try:
        device_id = int(device_id_raw) if device_id_raw is not None else 0
    except ValueError:
        device_id = 0

    try:
        poll_seconds = int(poll_seconds_raw) if poll_seconds_raw is not None else 0
    except ValueError:
        poll_seconds = 0

    cppdefines = []

    if ssid:
        cppdefines.append(("DEFAULT_WIFI_SSID", quote_define(ssid)))
    if pwd:
        cppdefines.append(("DEFAULT_WIFI_PASS", quote_define(pwd)))

    # Always pass server URL to ensure HTTPS/host is aligned with backend
    if server_url:
        cppdefines.append(("DEFAULT_SERVER_URL", quote_define(server_url)))

    if cppdefines and env is not None:
        env.Append(CPPDEFINES=cppdefines)

    header_path = project_dir / "include" / "DefaultBackendConfig.h"
    header_lines = [
        "// Auto-generated by pre_build_env.py. Do not edit manually.\n",
        "#pragma once\n",
        "\n",
    ]

    def add_define(name: str, value: Union[str, int], is_string: bool = True) -> None:
        if is_string:
            define_value = quote_define(value if isinstance(value, str) else str(value))
        else:
            define_value = str(int(value))
        header_lines.append(f"#define {name} {define_value}\n")

    add_define("DEFAULT_WIFI_SSID", ssid or "")
    add_define("DEFAULT_WIFI_PASS", pwd or "")
    add_define("DEFAULT_SERVER_URL", server_url or "")
    add_define("DEFAULT_HTTP_ACTIVATION_ENDPOINT", http_activation or "")
    add_define("DEFAULT_HTTP_STATE_ENDPOINT", http_state or "")
    add_define("DEFAULT_HTTP_SET_ENDPOINT", http_set or "")
    add_define("DEFAULT_HTTP_TELEMETRY_ENDPOINT", http_telemetry or "")
    add_define("DEFAULT_ACTIVATION_KEY", activation_key or "")
    add_define("DEFAULT_DEVICE_ID", device_id, is_string=False)
    add_define("DEFAULT_HTTP_POLL_SECONDS", poll_seconds, is_string=False)

    header_path.write_text("".join(header_lines), encoding="utf-8")


main()
