// Auto-generated by pre_build_env.py. Do not edit manually.
#pragma once

#define DEFAULT_WIFI_SSID ""
#define DEFAULT_WIFI_PASS ""
#define DEFAULT_SERVER_URL "https://proyecto.bisonbyte.io"
#define DEFAULT_HTTP_ACTIVATION_ENDPOINT ""
#define DEFAULT_HTTP_STATE_ENDPOINT ""
#define DEFAULT_HTTP_SET_ENDPOINT ""
#define DEFAULT_HTTP_TELEMETRY_ENDPOINT ""
#define DEFAULT_ACTIVATION_KEY ""
#define DEFAULT_DEVICE_ID 0
#define DEFAULT_HTTP_POLL_SECONDS 0
